# Generated by Django 4.1.13 on 2024-07-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=100)),
                ('secretario', models.CharField(max_length=100)),
                ('tesorero', models.CharField(max_length=100)),
                ('otros_miembros', models.TextField()),
                ('funciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('funciones', models.TextField()),
                ('informe_final', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('resultados', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ExCadete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=100)),
                ('historial_sanciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('cuota_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TribunalDeJusticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembros', models.TextField()),
                ('funciones', models.TextField()),
                ('resoluciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TablaDePosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.disciplina')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('evento_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.eventodeportivo')),
                ('ex_cadete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.excadete')),
            ],
        ),
        migrations.AddField(
            model_name='excadete',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.promocion'),
        ),
    ]
