# Generated by Django 4.1.13 on 2024-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_consejodirectivo_coordinadordeportivo_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunaldejusticia',
            name='archivos',
            field=models.FileField(default='', upload_to='archivos/'),
        ),
    ]
