# Generated by Django 4.1.13 on 2024-07-11 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0004_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
