# Generated by Django 4.1.13 on 2024-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0005_archivo_fecha_subida_alter_archivo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunaldejusticia',
            name='archivos',
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivos',
            field=models.FileField(default='', upload_to='archivos/'),
        ),
    ]
