# Generated by Django 4.1.13 on 2024-07-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0006_remove_tribunaldejusticia_archivos_archivo_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='archivos',
        ),
    ]
