# Generated by Django 4.1.13 on 2024-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0007_remove_archivo_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='categoria',
            field=models.CharField(choices=[('ORO-SUPER MASTER', 'Oro-Super Master'), ('MASTER', 'Master'), ('SUPER SENIORS', 'Super Seniors'), ('SENIORS', 'Seniors'), ('MAYORES', 'Mayores'), ('CADETES', 'Cadetes'), ('MENORES', 'Menores'), ('JUNIOR', 'Junior')], max_length=100),
        ),
    ]
