# Generated by Django 4.1.13 on 2024-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0008_alter_promocion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='promocion',
            name='jugadores',
            field=models.ManyToManyField(related_name='promociones', to='deportes.jugador'),
        ),
    ]
