# Generated by Django 5.0.7 on 2024-07-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0009_jugador_promocion_jugadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consejodirectivo',
            options={'verbose_name': 'Consejo directivo', 'verbose_name_plural': 'Consejo directivo'},
        ),
        migrations.AlterModelOptions(
            name='coordinadordeportivo',
            options={'verbose_name': 'Coordinador deportivo', 'verbose_name_plural': 'Coordinador deportivo'},
        ),
        migrations.AlterModelOptions(
            name='deportes',
            options={'verbose_name': 'Deportes', 'verbose_name_plural': 'Deportes'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='eventodeportivo',
            options={'verbose_name': 'Evento deportivo', 'verbose_name_plural': 'Evento deportivo'},
        ),
        migrations.AlterModelOptions(
            name='excadete',
            options={'verbose_name': 'Ex cadete', 'verbose_name_plural': 'Ex cadete'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugador'},
        ),
        migrations.AlterModelOptions(
            name='participacion',
            options={'verbose_name': 'Participación', 'verbose_name_plural': 'Participación'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promoción'},
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultado'},
        ),
        migrations.AlterModelOptions(
            name='tabladeposiciones',
            options={'verbose_name': 'Tabla de posiciones', 'verbose_name_plural': 'Tabla de posiciones'},
        ),
        migrations.AlterModelOptions(
            name='tribunaldejusticia',
            options={'verbose_name': 'Tribunal de justicia', 'verbose_name_plural': 'Tribunal de justicia'},
        ),
    ]
